---
- name: Restart Splunk Forwarder
  ansible.builtin.service:
    name: splunkforwarder
    state: restarted
  when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"

- name: Restart Splunk Forwarder (Windows)
  ansible.windows.win_service:
    name: SplunkForwarder
    state: restarted
  when: ansible_os_family == "Windows"
