---
- name: Check installed Splunk Forwarder version (Linux)
  ansible.builtin.command:
    cmd: "/opt/splunkforwarder/bin/splunk version"
  register: splunk_version_output
  when: os_family != "Windows"
  changed_when: false
  check_mode: no

- name: Check installed Splunk Forwarder version (Windows)
  ansible.windows.win_shell: "C:\\Program Files\\SplunkUniversalForwarder\\bin\\splunk.exe version"
  register: splunk_version_output
  when: os_family == "Windows"
  changed_when: false
  check_mode: no

- name: Set fact for installed Splunk Forwarder version
  ansible.builtin.set_fact:
    installed_splunk_version: "{{ splunk_version_output.stdout | regex_search('Splunk (\\S+)', '\\1') }}"

- name: Compare installed and desired Splunk Forwarder versions
  ansible.builtin.set_fact:
    splunk_version_mismatch: "{{ installed_splunk_version != splunk_version }}"
  when: installed_splunk_version is defined
