---
- name: Gather OS specific variables
  ansible.builtin.setup:
    gather_subset:
      - "all"

- name: Set OS family fact
  ansible.builtin.set_fact:
    os_family: "{{ ansible_os_family }}"

- name: Set OS version facts
  ansible.builtin.set_fact:
    os_version_major: "{{ ansible_distribution_major_version }}"
    os_version_minor: "{{ ansible_distribution_minor_version }}"
