---
- name: Stop Splunk Forwarder service (Linux)
  ansible.builtin.systemd:
    name: splunkforwarder
    state: stopped
  when: os_family != "Windows"

- name: Stop Splunk Forwarder service (Windows)
  ansible.windows.win_service:
    name: SplunkForwarder
    state: stopped
  when: os_family == "Windows"

- name: Remove existing Splunk Forwarder package (Linux)
  ansible.builtin.apt:
    name: splunkforwarder
    state: absent
  when: os_family != "Windows"

- name: Remove existing Splunk Forwarder package (Windows)
  ansible.windows.win_package:
    name: SplunkForwarder
    state: absent
  when: os_family == "Windows"
